base/account_manager/urls.py
from django.conf.urls import url, include

from . import views as account_manager_views
from . import cfsupport_views


cfsupport_urlpatterns = [
    url(r'^$', cfsupport_views.dashboard, name='cfsupport_dashboard'),
    url(r'^dashboard/$', cfsupport_views.dashboard, name='cfsupport_dashboard'),
    url(r'^search-transaction/$', cfsupport_views.search_transaction, name='search_transaction'),
    url(r'^edit-transaction/$', cfsupport_views.edit_transaction, name='edit_transaction'),
    url(r'^transactions/(?P<transaction_type>[a-zA-Z]+)/$', cfsupport_views.transactions, name='transactions'),
    url(r'^get-health-plans/', cfsupport_views.get_health_plans, name='transactions'),
    url(r'^offline-transaction/(?P<product_type>\w+)/$', cfsupport_views.add_offline_transaction, name='offline_transaction'),
    url(r'^user-accounts/$', cfsupport_views.user_accounts, name='user_accounts'),
    url(r'^transactions-vs-useraccounts/$', cfsupport_views.transactions_vs_useraccounts, name='transactions_vs_useraccounts'),
    url(r'^user/(?P<user_id>[0-9]+)$', cfsupport_views.user, name='user'),
    url(r'^login-as/$', cfsupport_views.login_as, name='login_as'),
    url(r'^staff-logout/$', cfsupport_views.staff_logout, name='staff_logout'),
    url(r'^endorsements/$', cfsupport_views.EndorsementListView.as_view(), name="endorsements"),
    url(r'^endorsements/add/$', cfsupport_views.endorsement_add, name="endorsement_add"),
    url(r'^endorsements/view/(?P<end_id>\d+)/$', cfsupport_views.endorsement_detail, name="endorsement_detail"),
    url(r'^endorsements/edit/(?P<end_id>\d+)/$', cfsupport_views.endorsement_edit, name="endorsement_edit"),
]

urlpatterns = [
    url(r'^profile/$', account_manager_views.profile, name='profile'),
    url(r'^policy/$', account_manager_views.policy, name='policy'),
    url(r'^expired/$', account_manager_views.expired, name='expired'),
    url(r'^submit-claim/$', account_manager_views.submit_claim, name='submit_claim'),
    url(r'^download-document/(?P<transaction_id>[\w-]+)/(?P<type>[a-zA-Z]+)/(?P<document_type>[a-zA-Z_]+)/$',
        account_manager_views.download_document, name='download_document'),
    url(r'^cfsupport/', include(cfsupport_urlpatterns)),
    url(r'^manage-policies/', account_manager_views.manage_policies, name='manage_policies'),
]

base/leads/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add/$', views.add, name='lead_add'),
    url(r'^save-call-time/$', views.save_call_time, name='lead_save_call_time'),
    url(r'^save-email/$', views.save_email, name='lead_save_email'),
    # api to for third party/generic lead save
    url(r'^save-lead/$', views.save_lead, name='lead_save'),
    url(r'^graphana-event/(?P<event_type>[\w]+)/$', views.graphana_event, name='graphana_event'),
    url(r'^send-otp/$', views.send_otp, name='send_otp'),
    url(r'^verify-otp/$', views.verify_otp, name='verify_otp'),
    url(r'^notify-customer-feedback', views.notify_customer_feedback, name='notify_customer_feedback')
    # url(r'^upload-document/$', views.upload_document,name='lead_upload_document'),
]

base/travel_product/urls.py
from django.conf.urls import include, url

from . import views

uuid_regex = '(%(hex)s{8}-%(hex)s{4}-%(hex)s{4}-%(hex)s{4}-%(hex)s{12})|(%(hex)s{32})' % {'hex': '[a-f0-9]'}

quote_urlpatterns = [
    url(r"^form/$", views.QuoteFormView.as_view(), name='form'),
    url(r"^result/$", views.SlabListView.as_view(), name='result'),
    url(r"^result/(?P<activity_id>%s)/$" % (uuid_regex,), views.SlabListView.as_view(), name='result'),
]

transaction_urlpatterns = [
    url(r'^$', views.TransactionListView.as_view(), name='home'),
    url(r'^add/$', views.TransactionCreateView.as_view(), name='add'),
    url(r'^(?P<transaction_id>%s)/$' % (uuid_regex,), views.BuyFormView.as_view(), name='buy'),
]

urlpatterns = [
    url(r'^', include(quote_urlpatterns, namespace='quote')),
    url(r'^buy/', include(transaction_urlpatterns, namespace='transaction')),

    #  uat urls
    url(r'^insurer/(?P<insurer_slug>[\w-]+)/$', views.search_form, name='search_form'),
    url(r'^insurer/(?P<insurer_slug>[\w-]+)/save-details/$', views.save_details, name='save_details'),
    url(r'^response/(?P<insurer_slug>[\w-]+)/(transaction/(?P<transaction_id>%s))?/$' % (uuid_regex,),
        views.payment_response, name='payment_response'),
    # TODO: remove before production (change position of response to as above)
    url(r'^(?P<insurer_slug>[\w-]+)/(transaction/(?P<transaction_id>%s)/)?response/$' % (uuid_regex,),
        views.payment_response, name='payment_response'),
    url(r'^insurer/(?P<insurer_slug>[\w-]+)/(transaction/(?P<transaction_id>%s)/)?response/$' % (uuid_regex,),
        views.payment_response, name='payment_response'),
    url(r'^insurer/(?P<insurer_slug>[\w-]+)/response/$', views.payment_response, name='payment_response'),
    url(r'^transaction/(?P<transaction_id>%s)/final/$' % (uuid_regex,),
        views.transaction_final, name='transaction_final'),
    url(r'^transaction/(?P<transaction_id>%s)/to-process/$' % (uuid_regex,), views.initiate_transaction_processing,
        name='initiate_transaction_processing'),
    url(r'^transaction/(?P<transaction_id>%s)/qa-to-process/$' % (uuid_regex, ), views.qa_make_payment,
        name='qa_make_payment'),
    url(r'^transaction/(?P<transaction_id>%s)/success/$' % (uuid_regex,),
        views.transaction_success, name='transaction_success'),
    url(r'^transaction/(?P<transaction_id>%s)/failure/$' % (uuid_regex,),
        views.transaction_failure, name='transaction_failure'),
    url(r'^get-state-city/(?P<pincode>[\w-]+)$', views.get_state_and_city, name='get_state_and_city'),
    url(r'^get-city-list$', views.get_city_list, name='get_city_list'),
    url(r'^send-to-lms/(?P<transaction_id>%s)/$' % uuid_regex, views.send_to_lms, name='send_to_lms'),
]

base/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as django_auth_views
from django.views.generic import RedirectView, TemplateView

from customforms import ajaxfield
from django_statsd.urls import urlpatterns as statsd_patterns
from motor_product.dealer.views import RegisterDealer
from motor_product.views import corporateDiscount


urlpatterns = [
    url(r'', include('home.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^cms/', include('cms.urls', namespace='cms')),
    url(r'^honcho/', admin.site.urls),
    url(r'^nimda/', RedirectView.as_view(permanent=True, pattern_name='admin:index')),
    url(r'^insurer/hospital/', TemplateView.as_view(template_name='flatpages:hospitals.html')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ajax/AjaxField/(?P<form_name>[\w-]+)/(?P<form_meta>[\w-]+)/$', ajaxfield.widget_url),
    url(r'^rupys-desk/', include('rdesk.urls')),
    url(r'^seo/', include('seo.urls')),
    url(r'^wiki/', include('wiki.urls')),
    url(r'^activity/', include('activity.urls')),
    url(r'^health-plan/', include('health_product.urls')),
    url(r'^health-plan/payment/', include('health_product.gateway.payu.urls')),
    url(r'^cardekho/', include('motor_product.motor_discount_code_admin.urls')),
    url(r'^mailer/', include('mailer.urls')),
    url(r'^motor/', include('motor_product.urls')),
    url(r'^motor/', include('payment.urls')),
    url(r'^travel-insurance/', include('travel_product.urls', namespace='travel')),
    url(r'^term-insurance/', include('life_product.urls', namespace='term')),
    url(r'^travel/', include('travel_product.urls')),
    url(r'^apis/', include('apis.urls')),
    url(r'^api/', include('apis.urls')),
    url(r'^cfadmin/', include('cfadmin.urls')),
    url(r'^user/', include('account_manager.urls', namespace='account_manager')),
    url(r'^lp/', include('campaign.urls', namespace='campaign')),
    url(r'^leads/', include('leads.urls', namespace='leads')),
    url(r'^accounts/login/$', django_auth_views.login, {'template_name': 'account_manager/login.html'}, 'user_login'),
    url(r'^accounts/logout/$', django_auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^accounts/register-dealer/$', RegisterDealer.as_view()),
    url(r'^marketing/', include('marketing.urls', namespace='marketing')),
    url(r'^otp/', include('otp.urls', namespace='otp')),
    url(r'^corporate/(?P<company>[\w-]+)/login/$', corporateDiscount, name='corporate_login'),
]

if not settings.PRODUCTION:
    urlpatterns += [url(r'^explorer/', include('explorer.urls'))]

urlpatterns += [
    url(r'', include('bakar.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('blog.urls')),
    url(r'', include('core.urls')),
    url(r'', include('campaign.flat_urls')),
    url(r'', include('wiki.flat_urls')),
    url(r'', include('brands.urls')),
    url(r'', include('seocms.urls')),
    url(r'', include('leaflet_campaign.urls', namespace='leaflet_campaign')),
    url(r'^services/timing/', include(statsd_patterns)),
    url(r'^pg/', include('payment_gateway.urls')),
    url(r'^app_notification/', include('app_notification.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = 'core.views.handle404'
# handler500 = 'core.views.handle500'
handler500 = 'bakar.views.server_error'
handler404 = 'bakar.views.page_not_found'
handler403 = 'bakar.views.page_not_found_403'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

urlpatterns += [
    url(r'', include('cfblog.urls')),
    ]

base/account_manager/apis/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator


alpha = RegexValidator(r'^[a-zA-Z ]+$', 'Only alphanumeric characters are allowed.')
numeric = RegexValidator(r'^[0-9]+$', 'Only numeric characters are allowed.')

class UpdateUserAccount(forms.Form):
    first_name = forms.CharField(max_length=50, validators=[alpha])
    middle_name = forms.CharField(max_length=50, required=False, validators=[alpha])
    last_name = forms.CharField(max_length=50, required=False, validators=[alpha])
    mobile = forms.CharField(max_length=10, required=False, validators=[numeric])
    address_line1 = forms.CharField(max_length=100, required=False)
    address_line2 = forms.CharField(max_length=100, required=False)
    address_landmark = forms.CharField(max_length=100, required=False, validators=[alpha])
    city = forms.CharField(max_length=100, validators=[alpha])
    state = forms.CharField(max_length=100, required=False, validators=[alpha])
    country = forms.CharField(max_length=100, required=False, validators=[alpha])
    pincode = forms.CharField(max_length=6, validators=[numeric])

    # def clean(self, *args, **kwargs):
    #     super(UpdateUserAccount, self).clean(*args, **kwargs)
    #     for key, value in self.cleaned_data.items():
    #         if not value:
    #             del self.cleaned_data[key]
    #     return self.cleaned_data


class CreateUser(forms.Form):
    first_name = forms.CharField(required=True, max_length=50, validators=[alpha])
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, max_length=20, min_length=6)

base/account_manager/forms.py
__author__ = "Parag Tyagi"

import os
from django import forms


def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1].lower()
    valid_extensions = ['.pdf']
    if ext not in valid_extensions:
        raise forms.ValidationError(
            u'Unsupported file extension. Please upload ({}) file'.format(', '.join(valid_extensions)))


class EditTransaction(forms.Form):
    policy_number = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(cut-copy-paste disabled)',
                'class': 'form-control cut-copy-paste-disabled',
                'type': 'password'
            }
        ),
        help_text='(refer document)'
    )
    re_enter_policy_number = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={'placeholder': '(cut-copy-paste disabled)', 'class': 'form-control cut-copy-paste-disabled'}
        )
    )
    premium_paid = forms.FloatField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(cut-copy-paste disabled)',
                'class': 'form-control cut-copy-paste-disabled',
                'type': 'password'
            }
        ),
        help_text='(refer document)'
    )
    re_enter_premium_paid = forms.FloatField(
        required=True,
        widget=forms.TextInput(
            attrs={'placeholder': '(cut-copy-paste disabled)', 'class': 'form-control cut-copy-paste-disabled'})
    )
    policy_document = forms.FileField(
        required=True,
        widget=forms.FileInput(attrs={'class': 'form-control', 'accept': '.pdf'}),
        validators=[validate_file_extension],
        help_text='(.pdf files only)'
    )
    payment_on = forms.DateTimeField(
        required=True,
        input_formats=['%Y/%m/%d %H:%M'],
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'datetimepicker_mask'}),
        help_text='(refer document)'
    )

    def clean(self):
        cleaned_data = super(EditTransaction, self).clean()

        # policy_number and re-enter
        if cleaned_data.get('policy_number') != cleaned_data.get('re_enter_policy_number'):
            self.add_error('re_enter_policy_number', u'Policy number(s) does not match.')

        # premium_paid and re-enter
        if cleaned_data.get('premium_paid') != cleaned_data.get('re_enter_premium_paid'):
            self.add_error('re_enter_premium_paid', u'Premium paid(s) does not match.')

        return cleaned_data

base/account_manager/templates/account_manager/cfsupport/base.html
<!DOCTYPE html>
{% load compress %}
<html lang="en">
<head>
<title>CF Support</title>
    <link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{{ STATIC_URL }}global/css/bootstrap-3.3.6.min.css">
    <!-- theme -->
    <link href="{{ STATIC_URL }}account_manager/css/cfsupport.css" rel="stylesheet" >
    <!--jQuery -->
    <script src="{{ STATIC_URL }}account_manager/js/jquery-1.11.3.min.js"></script>

    <style type="text/css">
    .step-numbers {
        border-radius:50px;
        padding:5px;
        width:30px;
        height:30px;
        text-align:center;
    }
    .bg-red {
        background-color: #f56954;
        color: white;
    }
    a:hover {
        text-decoration: none;
    }
    .container-fluid .jumbotron {
        padding:15px;
        padding-left: 32px;
    }
    .jumbotron p{
        font-size: 17px;
    }
    .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
        padding: 5px;
        font-size: 13px;
    }
    defaulttext:after {
        content: 'NA';
        font-style: italic;
        font-size: 10px;
    }
    .highlight {
        padding: 9px 14px;
        margin-bottom: 14px;
        background-color: #f7f7f9;
        border: 1px solid #e1e1e8;
        border-radius: 4px;
        font-size: 13px;
    }
    </style>

    {% block header_css %} {% endblock %}
    {% compress js %} {% block header_js %} {% endblock %} {% endcompress %}
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'account_manager:cfsupport_dashboard' %}">CF Support</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
      <li><a href="/user/profile/">My Profile</a></li>
        <li><a href="/accounts/logout/">Logout</a></li>
      </ul>
      <!-- <form action="{% url 'account_manager:search_transaction' %}" method="GET" class="navbar-form navbar-right">
        <input type="text" name="q" class="form-control" placeholder="Search transaction...">
      </form> -->
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">

    {% include 'account_manager/cfsupport/sidebar.html' %}

    {% block content %}{% endblock %}

  </div>
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="{{ STATIC_URL }}js/bootstrap-3.3.6.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
    /* Sidebar selection */
    var sel = $('.nav-sidebar').find("li[data-selected='{{ selected }}']");
    sel.children('ul').addClass('in');
    sel.addClass('active').siblings().removeClass('active');
});
    var CSRF_TOKEN = '{{ csrf_token }}';
</script>
{% block uncompressed_js %}{% endblock %}
{% compress js %} {% block footer_js %} {% endblock %} {% endcompress %}
{% block uncompressed_footer_js %} {% endblock %}
{% block footer_css %} {% endblock %}
</body>

</html>

base/account_manager/templates/account_manager/cfsupport/dashboard.html
{% extends 'account_manager/cfsupport/base.html' %}

{% block header_css %}
<link href="{{ STATIC_URL }}account_manager/css/jquery-ui.css" rel="stylesheet" >

<style type="text/css">
    .sub-heading {
        font-size:17px;
        font-style:italic;
    }
    .table-hover {
        border: 2px solid #ddd;
    }
    .table-hover tr:first-child {
        background-color: #ededed;
    }
    .table-hover th:first-child {
        background-color: #ededed;
    }
</style>
{% endblock %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h2 class="page-header">Dashboard</h2>

    <div class="row">
        <div class="col-sm-offset-2 col-md-offset-4">
            <form action="" method="GET" class="form-inline">
                <input type="text" name="from_date" class="datepicker form-control input-sm from-date" placeholder="From date" required />
                <input type="text" name="to_date" class="datepicker form-control input-sm to-date" placeholder="To date" required />
                <button type="submit" class="btn btn-primary btn-sm">Go</button>
                <a href="">
                    <button type="button" class="btn btn-primary btn-sm" title="Refresh filter">
                        <span class="glyphicon glyphicon-refresh"></span>
                    </button>
                </a>
                <a href="{% url 'account_manager:cfsupport_dashboard' %}">
                    <button type="button" class="btn btn-primary btn-sm" title="Reset filter">
                        <span class="glyphicon glyphicon-repeat"></span>
                    </button>
                </a>
            </form>

        </div>
    </div>

    <h3 class="sub-heading">Status report:</h3>
    <div class="row">
        <div class="col-md-6">
            <table class="table table-bordered table-hover">
                <tr>
                    <td></td>
                    <th>Car</th>
                    <th>Bike</th>
                    <th>Health</th>
                    <th>Travel</th>
                </tr>
                <tr>
                    <th>Payment successful <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Payment - done | Policy document - not uploaded"></span></th>
                    {% for count in report_count.successful.itervalues %}
                        <td>{{ count }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <th>Completed <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Payment - done | Policy document - uploaded"></span></th>
                    {% for count in report_count.completed.itervalues %}
                        <td>{{ count }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <th>Cancelled <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Transaction status - cancelled"></span></th>
                    {% for count in report_count.cancelled.itervalues %}
                        <td>{{ count }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <th>Pending <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Transaction status - pending"></span></th>
                    {% for count in report_count.pending.itervalues %}
                        <td>{{ count }}</td>
                    {% endfor %}
                </tr>
            </table>
        </div>

        <div class="col-md-6">
            <table class="table table-bordered table-hover">
                <tr>
                    <td></td>
                    <th>Car</th>
                    <th>Bike</th>
                    <th>Health</th>
                    <th>Travel</th>
                </tr>
                <tr>
                    <th>Endorsements</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Cancellation</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Claims</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>

    <h3 class="sub-heading">Insurer-wise Payment successful Policies ({{ total_count }}):</h3>

    {% include 'account_manager/cfsupport/paginator.html' %}

    <table class="table table-bordered table-hover">
        <tr>
            <th>Product</th>
            <th>Insurer</th>
            <th>Customer Name</th>
            <th>Mobile</th>
            <th>Transaction ID</th>
            <th>Pending since</th>
        </tr>
        {% if total_count > 0 %}
            {% for transaction in payment_success_transactions %}
                <tr>
                    <td>{{ transaction.type }}</td>
                    <td>{{ transaction.insurer_title }}</td>
                    <td>{{ transaction.first_name }}</td>
                    <td>{{ transaction.mobile }}</td>
                    <td><a href="{% url 'account_manager:edit_transaction' %}?transaction_id={{ transaction.transaction_id }}&transaction_type={{ transaction.type }}">{{ transaction.transaction_id }}</a></td>
                    <td>{{ transaction.transaction_created }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
              <td colspan="20" align="center" style="padding:30px; "><em>No results found.</em></td>
            </tr>
        {% endif %}
    </table>

</div>
{% endblock %}

{% block footer_js %}
<script src="{{ STATIC_URL }}account_manager/js/jquery-ui.js"></script>
<script>
  $(function() {
    $( ".datepicker" ).datepicker();
    $( ".datepicker" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
    $('[data-toggle="tooltip"]').tooltip();

    {% if from_date and to_date %}
    $( ".from-date" ).datepicker('setDate', "{{ from_date|date:'Y-m-d' }}");
    $( ".to-date" ).datepicker('setDate', "{{ to_date|date:'Y-m-d' }}");
    {% endif %}
  });
  </script>
{% endblock %}

base/account_manager/templates/account_manager/cfsupport/sidebar.html
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    {% if perms.account_manager.add_usertransaction or perms.account_manager.change_usertransaction %}
    <li data-selected='dashboard'><a href="{% url 'account_manager:cfsupport_dashboard' %}">Dashboard</a></li>
    <li data-selected='search-transaction'><a href="{% url 'account_manager:search_transaction' %}">Search transaction</a></li>
    <li data-selected='transactions'>
        <a class="accordion-heading" data-toggle="collapse" data-target="#submenu" style="cursor: pointer">
          <span class="nav-header-primary">All transactions <b class="caret"></b></span>
        </a>
        <ul class="nav nav-list collapse" id="submenu">
          <li><a href="{% url 'account_manager:transactions' 'car' %}" title="Car" style="padding-left:30px">Car</a></li>
          <li><a href="{% url 'account_manager:transactions' 'bike' %}" title="Bike" style="padding-left:30px">Bike</a></li>
          <li><a href="{% url 'account_manager:transactions' 'health' %}" title="Health" style="padding-left:30px">Health</a></li>
        <li><a href="{% url 'account_manager:transactions' 'travel' %}" title="Travel" style="padding-left:30px">Travel</a></li>
        </ul>
    </li>
    {% endif %}
    {% if perms.account_manager.add_offline_transaction %}
    <li data-selected='offline_transactions'>
        <a class="accordion-heading" data-toggle="collapse" data-target="#offline_submenu" style="cursor: pointer">
          <span class="nav-header-primary">Create offline transaction <b class="caret"></b></span>
        </a>
        <ul class="nav nav-list collapse" id="offline_submenu">
          <li><a href="{% url 'account_manager:offline_transaction' 'car' %}" title="Car" style="padding-left:30px">Car</a></li>
          <li><a href="{% url 'account_manager:offline_transaction' 'bike' %}" title="Bike" style="padding-left:30px">Bike</a></li>
          <li><a href="{% url 'account_manager:offline_transaction' 'health' %}" title="Health" style="padding-left:30px">Health</a></li>
        </ul>
    </li>
    {% endif %}
    {% if perms.account_manager.add_usertransaction or perms.account_manager.change_usertransaction %}
    <li data-selected='user-accounts'><a href="{% url 'account_manager:user_accounts' %}">User accounts</a></li>
    <li data-selected='transactions-vs-useraccounts'><a href="{% url 'account_manager:transactions_vs_useraccounts' %}">Transactions vs UserAccounts (Report)</a></li>
    <li data-selected='login-as'><a href="{% url 'account_manager:login_as' %}">Login as</a></li>
    {% endif %}
    {% if perms.core.add_endorsementdetail or perms.core.change_endorsementdetail or perms.core.view_endorsementdetail %}
    <li data-selected='endorsements'>
        <a class="accordion-heading" data-toggle="collapse" data-target="#endorsements_submenu" style="cursor: pointer">
          <span class="nav-header-primary">Endorsements<b class="caret"></b></span>
        </a>
        <ul class="nav nav-list collapse" id="endorsements_submenu">
          <li><a href="{% url 'account_manager:endorsements' %}" title="Dashboard" style="padding-left:30px">Dashboard</a></li>
          <li><a href="{% url 'account_manager:endorsement_add' %}" title="New" style="padding-left:30px">New</a></li>
        </ul>
    </li>
    {% endif %}
  </ul>
</div>

base/account_manager/templates/account_manager/cfsupport/user.html
{% extends 'account_manager/cfsupport/base.html' %}


{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h3 class="page-header">User detail</h3>

    <div class="row">
	    <div class="col-md-8 highlight">
	        {% include 'account_manager/cfsupport/user-detail.html' %}
	    </div>
    </div>

</div>
{% endblock %}